# docker-compose.yml
version: "3.3"

networks:
  web:
    external: true

services:
  traefik:
    image: traefik:alpine
    restart: always
    labels:
      - traefik.frontend.rule=Host:traefik.example.com
      - traefik.port=3333
      - traefik.enable=true

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik.toml:/etc/traefik/traefik.toml
    ports:
      - 3333:3333
      - 4444:4444
    networks:
      - web
