# docker-compose.yml
version: "3.3"

services:
  reverse-proxy:
    image: traefik:v2.7.0
    container_name: reverse-proxy
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./traefik/dynamic_conf.yml:/etc/traefik/dynamic_conf.yml"
      - "./traefik/acme.json:/etc/traefik/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # dashboard